version: '3.8'

services:
  wade-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wade-api-server
    ports:
      - "7860:7860"
    environment:
      - DB_PATH=wade_logs.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - URLSCAN_API_KEY=${URLSCAN_API_KEY}
      - GOOGLE_SAFE_BROWSING_API_KEY=${GOOGLE_SAFE_BROWSING_API_KEY}
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY}
    restart: always
